#!/bin/sh

set -e

. /usr/share/debconf/confmodule

Grub_File=/etc/default/grub
Theme_Dir=/boot/grub/themes

if [ "$1" = "configure" ]; then

	db_version 2.0

	# The following only on a new install
	if [ "$2" = "" ]; then
    echo "Instalando temas de grub por primera vez"
	fi

  db_get huayra-grub-themes/set_theme
	set_theme="$RET"

  if [ "$set_theme" = "true" ]; then

    db_get huayra-grub-themes/theme
    theme="$RET"

    if [ -f $Grub_File ];
    then
        echo "Comprobando si existe un thema actual en grub"
        i=$(sed -n 's,^#\?GRUB_THEME=,&,p' $Grub_File)

        if [ -z $i ]; then
            echo "Agregando tema al grub"
            echo "\nGRUB_THEME=$Theme_Dir/$theme/theme.txt" >>$Grub_File
        else
            echo "Reemplazando el tema actual por $theme"
            sed "s,^#\?GRUB_THEME=.*,GRUB_THEME=$Theme_Dir/$theme/theme.txt," <$Grub_File >$Grub_File.~
            mv $Grub_File.~ $Grub_File
        fi
        echo "Actualizando grub"
        update-grub
    fi
  fi
fi

#DEBHELPER#

exit 0
